version: 2.1

ruby_env: &ruby_env
  working_directory: ~/repo
  environment:
    BUNDLE_JOBS: 4
    BUNDLE_RETRY: 3
    BUNDLE_PATH: vendor/bundle
    RACK_ENV: test
    RAILS_ENV: test
    RUBY_VERSION: <<parameters.ruby-version>>
  docker:
    - image: circleci/ruby:<<parameters.ruby-version>>

executors:
  ruby_2_4:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.4"
  ruby_2_5:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.5"
  ruby_2_6:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.6"
  ruby_2_7:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.7"
  ruby_3_0:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.7"

commands:
  pre-setup:
    steps:
      - add_ssh_keys
      - checkout
  install-bundler:
    steps:
      - run:
          name: "Install bundler 1.17.3"
          command: |
            echo 'export BUNDLER_VERSION=1.17.3' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler:1.17.3
  benchmark:
    steps:
      - run: ./run.sh

jobs:
  benchmark:
    executor: <<parameters.e>>
    parameters:
      e:
        type: executor
        default: "ruby_2_6"
    steps:
      - pre-setup
      - install-bundler
      - benchmark

workflows:
  version: 2
  ruby_2_4:
    jobs:
      - benchmark:
          name: "ruby-2_4-benchmark"
          e: "ruby_2_4"
  ruby_2_5:
    jobs:
      - benchmark:
          name: "ruby-2_5-benchmark"
          e: "ruby_2_5"
  ruby_2_6:
    jobs:
      - benchmark:
          name: "ruby-2_6-benchmark"
          e: "ruby_2_6"
  ruby_2_7:
    jobs:
      - benchmark:
          name: "ruby-2_7-benchmark"
          e: "ruby_2_7"
  ruby_3_0:
    jobs:
      - benchmark:
          name: "ruby-3_0-benchmark"
          e: "ruby_3_0"
