version: 2.1

ruby_env: &ruby_env
  working_directory: ~/repo
  environment:
    BUNDLE_JOBS: 4
    BUNDLE_RETRY: 3
    BUNDLE_PATH: vendor/bundle
    RACK_ENV: test
    RAILS_ENV: test
    RUBY_VERSION: <<parameters.ruby-version>>
  docker:
    - image: cimg/ruby:<<parameters.ruby-version>>

executors:
  ruby_2_5:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.5"
  ruby_2_6:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.6"
  ruby_2_7:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.7"
  ruby_3_0:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "3.0"
  ruby_3_1:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "3.1"

commands:
  pre-setup:
    steps:
      - add_ssh_keys
      - checkout
  benchmark:
    steps:
      - run: ./run.sh

jobs:
  benchmark:
    executor: <<parameters.e>>
    parameters:
      e:
        type: executor
        default: "ruby_2_6"
    steps:
      - pre-setup
      - benchmark

workflows:
  version: 2
  ruby_2_5:
    jobs:
      - benchmark:
          name: "ruby-2_5-benchmark"
          e: "ruby_2_5"
  ruby_2_6:
    jobs:
      - benchmark:
          name: "ruby-2_6-benchmark"
          e: "ruby_2_6"
  ruby_2_7:
    jobs:
      - benchmark:
          name: "ruby-2_7-benchmark"
          e: "ruby_2_7"
  ruby_3_0:
    jobs:
      - benchmark:
          name: "ruby-2_7-benchmark"
          e: "ruby_3_0"
  ruby_3_1:
    jobs:
      - benchmark:
          name: "ruby-3_1-benchmark"
          e: "ruby_3_1"
